# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addToGeral.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_addGeral(object):
    def setupUi(self, addGeral):
        addGeral.setObjectName("addGeral")
        addGeral.resize(300, 617)
        self.gadoGroupBox = QtWidgets.QGroupBox(addGeral)
        self.gadoGroupBox.setGeometry(QtCore.QRect(20, 20, 261, 241))
        self.gadoGroupBox.setObjectName("gadoGroupBox")
        self.splitter_4 = QtWidgets.QSplitter(self.gadoGroupBox)
        self.splitter_4.setGeometry(QtCore.QRect(20, 200, 81, 20))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.totalLabel = QtWidgets.QLabel(self.splitter_4)
        self.totalLabel.setObjectName("totalLabel")
        self.totalSpinBox = QtWidgets.QSpinBox(self.splitter_4)
        self.totalSpinBox.setObjectName("totalSpinBox")
        self.widget = QtWidgets.QWidget(self.gadoGroupBox)
        self.widget.setGeometry(QtCore.QRect(20, 20, 115, 72))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.categoriaLabel = QtWidgets.QLabel(self.splitter)
        self.categoriaLabel.setObjectName("categoriaLabel")
        self.categoriaComboBox = QtWidgets.QComboBox(self.splitter)
        self.categoriaComboBox.setObjectName("categoriaComboBox")
        self.categoriaComboBox.addItem("")
        self.categoriaComboBox.addItem("")
        self.categoriaComboBox.addItem("")
        self.categoriaComboBox.addItem("")
        self.verticalLayout.addWidget(self.splitter)
        spacerItem = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.splitter_2 = QtWidgets.QSplitter(self.widget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.sexoLabel = QtWidgets.QLabel(self.splitter_2)
        self.sexoLabel.setObjectName("sexoLabel")
        self.sexoComboBox = QtWidgets.QComboBox(self.splitter_2)
        self.sexoComboBox.setObjectName("sexoComboBox")
        self.sexoComboBox.addItem("")
        self.sexoComboBox.addItem("")
        self.verticalLayout.addWidget(self.splitter_2)
        self.widget1 = QtWidgets.QWidget(self.gadoGroupBox)
        self.widget1.setGeometry(QtCore.QRect(20, 100, 236, 69))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.nascidoCheckBox = QtWidgets.QCheckBox(self.widget1)
        self.nascidoCheckBox.setChecked(False)
        self.nascidoCheckBox.setTristate(False)
        self.nascidoCheckBox.setObjectName("nascidoCheckBox")
        self.verticalLayout_2.addWidget(self.nascidoCheckBox)
        self.splitter_3 = QtWidgets.QSplitter(self.widget1)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.dataNascimentoLabel = QtWidgets.QLabel(self.splitter_3)
        self.dataNascimentoLabel.setObjectName("dataNascimentoLabel")
        self.dataNascimentoDateTime = QtWidgets.QDateTimeEdit(self.splitter_3)
        self.dataNascimentoDateTime.setEnabled(False)
        self.dataNascimentoDateTime.setObjectName("dataNascimentoDateTime")
        self.verticalLayout_2.addWidget(self.splitter_3)
        self.splitter.raise_()
        self.splitter_2.raise_()
        self.nascidoCheckBox.raise_()
        self.splitter_3.raise_()
        self.splitter_4.raise_()
        self.splitter_3.raise_()
        self.acontecimentoCheckBox = QtWidgets.QCheckBox(addGeral)
        self.acontecimentoCheckBox.setGeometry(QtCore.QRect(30, 280, 101, 17))
        self.acontecimentoCheckBox.setObjectName("acontecimentoCheckBox")
        self.acontecimentoGroupBox = QtWidgets.QGroupBox(addGeral)
        self.acontecimentoGroupBox.setEnabled(False)
        self.acontecimentoGroupBox.setGeometry(QtCore.QRect(20, 310, 271, 251))
        self.acontecimentoGroupBox.setObjectName("acontecimentoGroupBox")
        self.splitter_5 = QtWidgets.QSplitter(self.acontecimentoGroupBox)
        self.splitter_5.setGeometry(QtCore.QRect(20, 30, 241, 20))
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.dataAcontecimentoLabel = QtWidgets.QLabel(self.splitter_5)
        self.dataAcontecimentoLabel.setObjectName("dataAcontecimentoLabel")
        self.dataAcontecimentoDateTime = QtWidgets.QDateTimeEdit(self.splitter_5)
        self.dataAcontecimentoDateTime.setObjectName("dataAcontecimentoDateTime")
        self.splitter_6 = QtWidgets.QSplitter(self.acontecimentoGroupBox)
        self.splitter_6.setGeometry(QtCore.QRect(20, 70, 152, 20))
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.acontecimentoLabel = QtWidgets.QLabel(self.splitter_6)
        self.acontecimentoLabel.setObjectName("acontecimentoLabel")
        self.acontecimentoComboBox = QtWidgets.QComboBox(self.splitter_6)
        self.acontecimentoComboBox.setObjectName("acontecimentoComboBox")
        self.acontecimentoComboBox.addItem("")
        self.acontecimentoComboBox.addItem("")
        self.acontecimentoComboBox.addItem("")
        self.acontecimentoComboBox.addItem("")
        self.acontecimentoComboBox.addItem("")
        self.splitter_7 = QtWidgets.QSplitter(self.acontecimentoGroupBox)
        self.splitter_7.setGeometry(QtCore.QRect(20, 110, 231, 131))
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName("splitter_7")
        self.descricaoLabel = QtWidgets.QLabel(self.splitter_7)
        self.descricaoLabel.setObjectName("descricaoLabel")
        self.descricaoTextEdit = QtWidgets.QTextEdit(self.splitter_7)
        self.descricaoTextEdit.setObjectName("descricaoTextEdit")
        self.adicionarPushButton = QtWidgets.QPushButton(addGeral)
        self.adicionarPushButton.setGeometry(QtCore.QRect(30, 580, 75, 23))
        self.adicionarPushButton.setObjectName("adicionarPushButton")
        self.limparPushButton = QtWidgets.QPushButton(addGeral)
        self.limparPushButton.setGeometry(QtCore.QRect(110, 580, 75, 23))
        self.limparPushButton.setObjectName("limparPushButton")
        self.cancelarPushButton = QtWidgets.QPushButton(addGeral)
        self.cancelarPushButton.setGeometry(QtCore.QRect(190, 580, 75, 23))
        self.cancelarPushButton.setObjectName("cancelarPushButton")

        self.retranslateUi(addGeral)
        self.categoriaComboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(addGeral)

    def retranslateUi(self, addGeral):
        _translate = QtCore.QCoreApplication.translate
        addGeral.setWindowTitle(_translate("addGeral", "Dialog"))
        self.gadoGroupBox.setTitle(_translate("addGeral", "Gado"))
        self.totalLabel.setText(_translate("addGeral", "Total:"))
        self.categoriaLabel.setText(_translate("addGeral", "Categoria: "))
        self.categoriaComboBox.setItemText(0, _translate("addGeral", "Boi"))
        self.categoriaComboBox.setItemText(1, _translate("addGeral", "Vaca"))
        self.categoriaComboBox.setItemText(2, _translate("addGeral", "Touro"))
        self.categoriaComboBox.setItemText(3, _translate("addGeral", "Vitelo"))
        self.sexoLabel.setText(_translate("addGeral", "Sexo:"))
        self.sexoComboBox.setItemText(0, _translate("addGeral", "M"))
        self.sexoComboBox.setItemText(1, _translate("addGeral", "F"))
        self.nascidoCheckBox.setText(_translate("addGeral", "Nascido"))
        self.dataNascimentoLabel.setText(_translate("addGeral", "Data de Nascimento:"))
        self.acontecimentoCheckBox.setText(_translate("addGeral", "Acontecimento"))
        self.acontecimentoGroupBox.setTitle(_translate("addGeral", "Acontecimento"))
        self.dataAcontecimentoLabel.setText(_translate("addGeral", "Data do Acontecimento"))
        self.acontecimentoLabel.setText(_translate("addGeral", "Acontecimento"))
        self.acontecimentoComboBox.setItemText(0, _translate("addGeral", "Morte"))
        self.acontecimentoComboBox.setItemText(1, _translate("addGeral", "Retirada"))
        self.acontecimentoComboBox.setItemText(2, _translate("addGeral", "Nascimento"))
        self.acontecimentoComboBox.setItemText(3, _translate("addGeral", "Ferimento"))
        self.acontecimentoComboBox.setItemText(4, _translate("addGeral", "Roubo"))
        self.descricaoLabel.setText(_translate("addGeral", "Descricao:"))
        self.adicionarPushButton.setText(_translate("addGeral", "Adicionar"))
        self.limparPushButton.setText(_translate("addGeral", "Limpar"))
        self.cancelarPushButton.setText(_translate("addGeral", "Cancelar"))

