# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addToNovo.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_addToNovo(object):
    def setupUi(self, addToNovo):
        addToNovo.setObjectName("addToNovo")
        addToNovo.resize(322, 319)
        self.origemGroupBox = QtWidgets.QGroupBox(addToNovo)
        self.origemGroupBox.setGeometry(QtCore.QRect(20, 130, 291, 121))
        self.origemGroupBox.setCheckable(False)
        self.origemGroupBox.setObjectName("origemGroupBox")
        self.producaoInternaCheckBox = QtWidgets.QCheckBox(self.origemGroupBox)
        self.producaoInternaCheckBox.setGeometry(QtCore.QRect(10, 70, 111, 17))
        self.producaoInternaCheckBox.setChecked(True)
        self.producaoInternaCheckBox.setObjectName("producaoInternaCheckBox")
        self.splitter_5 = QtWidgets.QSplitter(self.origemGroupBox)
        self.splitter_5.setGeometry(QtCore.QRect(10, 90, 261, 20))
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.dataNascimentoLabel = QtWidgets.QLabel(self.splitter_5)
        self.dataNascimentoLabel.setObjectName("dataNascimentoLabel")
        self.dataNascimentoDateTimeEdit = QtWidgets.QDateTimeEdit(self.splitter_5)
        self.dataNascimentoDateTimeEdit.setObjectName("dataNascimentoDateTimeEdit")
        self.compradoCheckBox = QtWidgets.QCheckBox(self.origemGroupBox)
        self.compradoCheckBox.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.compradoCheckBox.setObjectName("compradoCheckBox")
        self.splitter_4 = QtWidgets.QSplitter(self.origemGroupBox)
        self.splitter_4.setGeometry(QtCore.QRect(10, 40, 241, 20))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.dataCompraLabel = QtWidgets.QLabel(self.splitter_4)
        self.dataCompraLabel.setObjectName("dataCompraLabel")
        self.dataCompraDateTimeEdit = QtWidgets.QDateTimeEdit(self.splitter_4)
        self.dataCompraDateTimeEdit.setEnabled(False)
        self.dataCompraDateTimeEdit.setObjectName("dataCompraDateTimeEdit")
        self.producaoInternaCheckBox.raise_()
        self.splitter_5.raise_()
        self.splitter_4.raise_()
        self.compradoCheckBox.raise_()
        self.splitter_4.raise_()
        self.producaoInternaCheckBox.raise_()
        self.splitter_5.raise_()
        self.compradoCheckBox.raise_()
        self.adicionarPushButton = QtWidgets.QPushButton(addToNovo)
        self.adicionarPushButton.setGeometry(QtCore.QRect(40, 280, 75, 23))
        self.adicionarPushButton.setObjectName("adicionarPushButton")
        self.limparPushButton = QtWidgets.QPushButton(addToNovo)
        self.limparPushButton.setGeometry(QtCore.QRect(120, 280, 75, 23))
        self.limparPushButton.setObjectName("limparPushButton")
        self.cancelarPushButton = QtWidgets.QPushButton(addToNovo)
        self.cancelarPushButton.setGeometry(QtCore.QRect(200, 280, 75, 23))
        self.cancelarPushButton.setObjectName("cancelarPushButton")
        self.widget = QtWidgets.QWidget(addToNovo)
        self.widget.setGeometry(QtCore.QRect(20, 20, 125, 101))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.categoriaLabel = QtWidgets.QLabel(self.splitter)
        self.categoriaLabel.setObjectName("categoriaLabel")
        self.categoriaComboBox = QtWidgets.QComboBox(self.splitter)
        self.categoriaComboBox.setObjectName("categoriaComboBox")
        self.categoriaComboBox.addItem("")
        self.categoriaComboBox.addItem("")
        self.categoriaComboBox.addItem("")
        self.categoriaComboBox.addItem("")
        self.verticalLayout.addWidget(self.splitter)
        spacerItem = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.splitter_2 = QtWidgets.QSplitter(self.widget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.sexoLabel = QtWidgets.QLabel(self.splitter_2)
        self.sexoLabel.setObjectName("sexoLabel")
        self.sexoComboBox = QtWidgets.QComboBox(self.splitter_2)
        self.sexoComboBox.setObjectName("sexoComboBox")
        self.sexoComboBox.addItem("")
        self.sexoComboBox.addItem("")
        self.verticalLayout.addWidget(self.splitter_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.splitter_3 = QtWidgets.QSplitter(self.widget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.totalLabel = QtWidgets.QLabel(self.splitter_3)
        self.totalLabel.setObjectName("totalLabel")
        self.totalComboBox = QtWidgets.QSpinBox(self.splitter_3)
        self.totalComboBox.setObjectName("totalComboBox")
        self.verticalLayout.addWidget(self.splitter_3)

        self.retranslateUi(addToNovo)
        QtCore.QMetaObject.connectSlotsByName(addToNovo)

    def retranslateUi(self, addToNovo):
        _translate = QtCore.QCoreApplication.translate
        addToNovo.setWindowTitle(_translate("addToNovo", "Dialog"))
        self.origemGroupBox.setTitle(_translate("addToNovo", "Origem"))
        self.producaoInternaCheckBox.setText(_translate("addToNovo", "Producao Interna"))
        self.dataNascimentoLabel.setText(_translate("addToNovo", "Data de Nascimento:"))
        self.compradoCheckBox.setText(_translate("addToNovo", "Comprado"))
        self.dataCompraLabel.setText(_translate("addToNovo", "Data de Compra:"))
        self.adicionarPushButton.setText(_translate("addToNovo", "Adicionar"))
        self.limparPushButton.setText(_translate("addToNovo", "Limpar"))
        self.cancelarPushButton.setText(_translate("addToNovo", "Cancelar"))
        self.categoriaLabel.setText(_translate("addToNovo", "Categoria:"))
        self.categoriaComboBox.setItemText(0, _translate("addToNovo", "Boi"))
        self.categoriaComboBox.setItemText(1, _translate("addToNovo", "Vaca"))
        self.categoriaComboBox.setItemText(2, _translate("addToNovo", "Touro"))
        self.categoriaComboBox.setItemText(3, _translate("addToNovo", "Vitelo"))
        self.sexoLabel.setText(_translate("addToNovo", "Sexo: "))
        self.sexoComboBox.setItemText(0, _translate("addToNovo", "M"))
        self.sexoComboBox.setItemText(1, _translate("addToNovo", "F"))
        self.totalLabel.setText(_translate("addToNovo", "Total"))

