# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/chernomirdinmacuvele/Documents/workspace/Cural1.0/UserInt/ViewData.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1036, 557)
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.TV = QtWidgets.QTableView(Form)
        self.TV.setObjectName("TV")
        self.gridLayout_4.addWidget(self.TV, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 2)
        self.PBEditIR = QtWidgets.QPushButton(Form)
        self.PBEditIR.setObjectName("PBEditIR")
        self.gridLayout_2.addWidget(self.PBEditIR, 7, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 2)
        self.PBAddIM = QtWidgets.QPushButton(Form)
        self.PBAddIM.setObjectName("PBAddIM")
        self.gridLayout_2.addWidget(self.PBAddIM, 5, 0, 1, 1)
        self.PBEditIN = QtWidgets.QPushButton(Form)
        self.PBEditIN.setObjectName("PBEditIN")
        self.gridLayout_2.addWidget(self.PBEditIN, 3, 1, 1, 1)
        self.PBAddIN = QtWidgets.QPushButton(Form)
        self.PBAddIN.setObjectName("PBAddIN")
        self.gridLayout_2.addWidget(self.PBAddIN, 3, 0, 1, 1)
        self.PBEditIG = QtWidgets.QPushButton(Form)
        self.PBEditIG.setObjectName("PBEditIG")
        self.gridLayout_2.addWidget(self.PBEditIG, 1, 1, 1, 1)
        self.PBFechar = QtWidgets.QPushButton(Form)
        self.PBFechar.setObjectName("PBFechar")
        self.gridLayout_2.addWidget(self.PBFechar, 8, 0, 1, 2)
        self.PBAddIR = QtWidgets.QPushButton(Form)
        self.PBAddIR.setObjectName("PBAddIR")
        self.gridLayout_2.addWidget(self.PBAddIR, 7, 0, 1, 1)
        self.PBAddIG = QtWidgets.QPushButton(Form)
        self.PBAddIG.setObjectName("PBAddIG")
        self.gridLayout_2.addWidget(self.PBAddIG, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 2)
        self.PBEditIM = QtWidgets.QPushButton(Form)
        self.PBEditIM.setObjectName("PBEditIM")
        self.gridLayout_2.addWidget(self.PBEditIM, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 6, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.LBRemovidos = QtWidgets.QLabel(Form)
        self.LBRemovidos.setObjectName("LBRemovidos")
        self.gridLayout_3.addWidget(self.LBRemovidos, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 2, 1, 1)
        self.LBMorto = QtWidgets.QLabel(Form)
        self.LBMorto.setObjectName("LBMorto")
        self.gridLayout_3.addWidget(self.LBMorto, 0, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 4, 1, 1)
        self.LBExistente = QtWidgets.QLabel(Form)
        self.LBExistente.setObjectName("LBExistente")
        self.gridLayout_3.addWidget(self.LBExistente, 0, 5, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.DTEDataNascimento = QtWidgets.QDateTimeEdit(Form)
        self.DTEDataNascimento.setObjectName("DTEDataNascimento")
        self.gridLayout.addWidget(self.DTEDataNascimento, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 4, 1, 1)
        self.CBSexo = QtWidgets.QComboBox(Form)
        self.CBSexo.setObjectName("CBSexo")
        self.gridLayout.addWidget(self.CBSexo, 0, 5, 1, 1)
        self.PBSexo = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBSexo.sizePolicy().hasHeightForWidth())
        self.PBSexo.setSizePolicy(sizePolicy)
        self.PBSexo.setObjectName("PBSexo")
        self.gridLayout.addWidget(self.PBSexo, 0, 6, 1, 1)
        self.CBCagegoria = QtWidgets.QComboBox(Form)
        self.CBCagegoria.setObjectName("CBCagegoria")
        self.gridLayout.addWidget(self.CBCagegoria, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Visualizar"))
        self.label_4.setText(_translate("Form", "Geral"))
        self.PBEditIR.setText(_translate("Form", "Edit"))
        self.label_6.setText(_translate("Form", "Mortos"))
        self.PBAddIM.setText(_translate("Form", "Add"))
        self.PBEditIN.setText(_translate("Form", "Edit"))
        self.PBAddIN.setText(_translate("Form", "Add"))
        self.PBEditIG.setText(_translate("Form", "Edit"))
        self.PBFechar.setText(_translate("Form", "Close"))
        self.PBAddIR.setText(_translate("Form", "Add"))
        self.PBAddIG.setText(_translate("Form", "Add"))
        self.label_5.setText(_translate("Form", "Novos"))
        self.PBEditIM.setText(_translate("Form", "Edit"))
        self.label_7.setText(_translate("Form", "Retirados"))
        self.label_8.setText(_translate("Form", "Total de Gado Removido:"))
        self.LBRemovidos.setText(_translate("Form", "--"))
        self.label_10.setText(_translate("Form", "Total de Gado Morto:"))
        self.LBMorto.setText(_translate("Form", "--"))
        self.label_12.setText(_translate("Form", "Total de Gado Existente:"))
        self.LBExistente.setText(_translate("Form", "--"))
        self.DTEDataNascimento.setDisplayFormat(_translate("Form", "dd/MM/yyyy"))
        self.label_2.setText(_translate("Form", "Categoria:"))
        self.label_3.setText(_translate("Form", "Sexo:"))
        self.PBSexo.setText(_translate("Form", "Search"))
        self.label.setText(_translate("Form", "Data De Nascimento:"))
